name: Manual
env:
  CI: true
  FORCE_COLOR: 1
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/ms-playwright
on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r --filter metamask-testing-tools exec playwright install --with-deps
      - run: pnpm -r --filter metamask-testing-tools run test
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/testing/playwright-report/
          retention-days: 30
      - run: POSTMARK_SERVER_TOKEN=${{ secrets.POSTMARK_TOKEN }} npx postmark-cli email raw -f "CI Notifications <ci@decentralised.dev>" -t hugomrdias@gmail.com --subject "[${{github.repository}}] Workflow Failed" --html "Workflow <b>${{ github.workflow }}</b> Job <b>${{ github.job}}</b> failed! <br/> ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        if: failure()